name: Gernerate ASCII workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checksout repo
              uses: actions/checkout@v4
            
            - name: Install cowsay repo
              uses: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              uses: cowsay -f dolphin "AM coming in hot" >> df.txt
            
            - name: tests if the file is there
              uses: grep -i "dolphin" df.txt

            - name: read the file 
              uses: cat df.txt

            - name: Checkout Repo files
              uses: ls -ltr

            - name: echo something
              uses: echo "what the heck"