name: Gernerate ASCII workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checksout repo
              uses: actions/checkout@v4

            - name: List the repo files
              run: ls -ltra
            
            - name: Initiaite the shell script 
              run: ./ascii-script.sh

            