name: Gernerate ASCII workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checksout repo
              uses: actions/checkout@v4
            
            - name: Install cowsay repo
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "AM coming in hot" >> dragon.txt
            
            # - name: tests if the file is there
            #   run: grep -i "dragon" dragon.txt

            - name: read the file 
              run: cat dragon.txt

            - name: Checkout Repo files
              run: ls -ltr

            - name: echo something
              run: echo "what the heck is that"

              #