name: Prodesparate
on: push
jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: apt install
              run: sudo apt-get install  cowsay -y

            - name: ascii generate
              run: cowsay -f dragon "AM coming in hot" >> dragon.txt

            - name: upload the file
              uses: actions/upload-artifact@v4
              with:
                name: upload it
                path: dragon.txt

    third-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: download the file
              uses: actions/download-artifact@v4
              with:
                name: upload it

            - name: display ascii
              run: |
                ls -ltra
                cat dragon.txt